[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "embedding-classifier"
version = "0.0.1"
description = "training classification model using embeddings"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []
